version: "3"

volumes:
  certs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,ro
      device: :/nfs/Data/linux/certs
  jalousie:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/jalousie
  nas_fritzbox:
    # //fritz.nas/fritz.nas/FritzBox/NAS /mnt/fritzbox_nas cifs username=nas,passwd= 0 0
    driver: cifs
    driver_opts:
#      share: //fritz.nas/fritz.nas/FritzBox/NAS
#      share: 192.168.6.1/fritz.nas/FritzBox/NAS
      share: fritz.nas/fritz.nas/FritzBox/NAS
      username: nas
      passwd: "nas1"
      password: "nas2"
  portainer:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/portainer
  postfix_creds:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,ro
      device: :/nfs/Data/linux/postfix_creds
  postfix_spool:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/postfix_spool
  twonky:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/twonky
  vito:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/vito
  vmail:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/vmail
  www:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/www

networks:
  backend:
    driver: bridge

services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer
    ports:
      - 8008:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data:nocopy
  nginx:
    restart: unless-stopped
    build: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - certs:/etc/nginx/certs:nocopy
    links:
      - apache2
  dovecot:
    restart: unless-stopped
    build: dovecot
    ports:
      - 993:993
    volumes:
      - certs:/etc/dovecot/certs:nocopy
      - vmail:/home/vmail:nocopy
  pigpiod:
    restart: unless-stopped
    build: pigpiod
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/mem:/dev/mem
      - /dev/vcio:/dev/vcio
    networks:
      - backend
    ports:
      - 8888:8888
  apache2:
    restart: unless-stopped
    build: apache2
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - jalousie:/var/jalousie:nocopy
      - vito:/var/vito:nocopy
      - www:/var/www:nocopy
    links:
      - jalousie
  jalousie:
    restart: unless-stopped
    build: jalousie
    ports:
      - 9124:9124
    networks:
      - backend
    volumes:
      - jalousie:/var/jalousie:nocopy
      - vito:/var/vito:nocopy,ro
    links:
      - postfix
      - pigpiod
  vito:
    restart: unless-stopped
    build: vito
    networks:
      - backend
    volumes:
      - vito:/var/vito:nocopy
    links:
      - postfix
      - vcontrold
  postfix:
    restart: unless-stopped
    build: postfix
    ports:
      - "25:25"
    networks:
      - backend
    volumes:
      - postfix_creds:/postfix_creds:nocopy
# TODO      - postfix_spool:/var/spool/postfix:nocopy
  vcontrold:
    restart: unless-stopped
    build: vcontrold
    ports:
      - 3002:3002
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    networks:
      - backend
  twonky:
    restart: unless-stopped
    build: twonky
    # Note: 'network_mode: host' is required for twonky to receive multicast traffic to detect the upnp server.
    network_mode: host
    ports:
      - 1030:1030/udp
      - 1900:1900/udp
      - 9000:9000
    volumes:
      - nas_fritzbox:/mnt/nas_fritzbox:nocopy
      - twonky:/var/twonky:nocopy
