version: "3"

volumes:
  certs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,ro
      device: :/nfs/Data/linux/certs
  jalousie:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/jalousie
  portainer:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/portainer
  postfix_creds:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,ro
      device: :/nfs/Data/linux/postfix_creds
  postfix_spool:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/postfix_spool
  vito:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/vito
  vmail:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/vmail
  www:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/www

networks:
  backend:
    driver: bridge

services:
  portainer:
    restart: always
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data:nocopy
  nginx:
    restart: always
    build: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - certs:/etc/nginx/certs:nocopy
    links:
      - apache2
  dovecot:
    restart: always
    build: dovecot
    ports:
      - 993:993
    volumes:
      - certs:/etc/dovecot/certs:nocopy
      - vmail:/home/vmail:nocopy
  pigpiod:
    restart: always
    build: pigpiod
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/mem:/dev/mem
      - /dev/vcio:/dev/vcio
    networks:
      - backend
    ports:
      - 8888:8888
  apache2:
    restart: always
    build: apache2
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - jalousie:/var/jalousie:nocopy
      - vito:/var/vito:nocopy
      - www:/var/www:nocopy
    links:
      - jalousie
  jalousie:
    restart: always
    build: jalousie
    ports:
      - 9124:9124
    networks:
      - backend
    volumes:
      - jalousie:/var/jalousie:nocopy
      - vito:/var/vito:nocopy,ro
    links:
      - postfix
      - pigpiod
  vito:
    restart: always
    build: vito
    networks:
      - backend
    volumes:
      - vito:/var/vito:nocopy
    links:
      - postfix
      - vcontrold
  postfix:
    restart: always
    build: postfix
    ports:
      - "25:25"
    networks:
      - backend
    volumes:
      - postfix_creds:/postfix_creds:nocopy
# TODO      - postfix_spool:/var/spool/postfix:nocopy
  vcontrold:
    restart: always
    build: vcontrold
    ports:
      - 3002:3002
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    networks:
      - backend
